# **FRAMEWORK V7 DATASET MAESTRO - PREPARACION PARA MACHINE LEARNING**

## **M0. Configuración**

In [2]:
import pandas as pd

#==========================================================================================
# CARGA DEL DATASET MAESTRO
#==========================================================================================

url_dataset = (

"https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C09_MASTER/Dataset_Maestro_Framework_v04.parquet"

)

dataset = pd.read_parquet(url_dataset)

print()

print("="*90)
print("DATASET MAESTRO")
print("="*90)

print()

print(f"Observaciones : {dataset.shape[0]}")

print(f"Variables     : {dataset.shape[1]}")

==========================================================================================
DATASET MAESTRO
==========================================================================================

Observaciones : 528
Variables     : 42

## **M1. Construcción del Dataset Optimizado para Machine Learning**

In [5]:
#==========================================================================================
# VARIABLES SELECCIONADAS
#==========================================================================================

url_variables = (

"https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C11_MASTER/Preparacion_Machine_Learning/ipm/variables_machine_learning.csv"

)

variables_ml = pd.read_csv(url_variables)

print()

print("="*90)
print("VARIABLES SELECCIONADAS")
print("="*90)

print()

print(f"Variables : {len(variables_ml)}")

display(variables_ml.head())

==========================================================================================
VARIABLES SELECCIONADAS
==========================================================================================

Variables : 9

,Ranking,Variable,Tipo,Relaciones_Fuertes,Indice_Redundancia,Nivel_Redundancia,Diagnostico_Redundancia,VIF,Estado_VIF,Diagnostico_VIF,...,Importancia,Peso,Puntaje_Conocimiento_Dominio,% Cobertura,Puntaje_Calidad,Puntaje_Redundancia,Puntaje_Multicolinealidad,IPML,Nivel_IPML,Estado_Final
0,1,Precipitacion_mm,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,1.898,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.0,100.0,1.0,1.0,1.00,1.00,Muy Alta,Seleccionada
1,2,ONI,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,1.265,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.0,100.0,1.0,1.0,1.00,1.00,Muy Alta,Seleccionada
2,3,Radiacion_Solar,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,1.704,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.0,100.0,1.0,1.0,1.00,1.00,Muy Alta,Seleccionada
3,4,Humedad_Relativa,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,7.128,Moderada,Existe una dependencia moderada aceptable para...,...,Muy Alta,3,1.0,100.0,1.0,1.0,0.75,0.95,Muy Alta,Seleccionada
4,8,Temp_Min_C,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,10.573,Alta,Presenta una dependencia considerable con otra...,...,Muy Alta,3,1.0,100.0,1.0,1.0,0.50,0.90,Muy Alta,Seleccionada

In [6]:
#==========================================================================================
# LISTA DE VARIABLES
#==========================================================================================

lista_variables = variables_ml["Variable"].tolist()

print()

print("="*90)
print("VARIABLES UTILIZADAS")
print("="*90)

for variable in lista_variables:

    print(variable)

==========================================================================================
VARIABLES UTILIZADAS
==========================================================================================
Precipitacion_mm
ONI
Radiacion_Solar
Humedad_Relativa
Temp_Min_C
Mes
Velocidad_Viento
irca
VolumenUtilDiarioMasa

In [7]:
#==========================================================================================
# VALIDACIÓN DE VARIABLES
#==========================================================================================

faltantes = [

    variable

    for variable in lista_variables

    if variable not in dataset.columns

]

print()

print("="*90)
print("VALIDACIÓN")
print("="*90)

print()

if len(faltantes)==0:

    print("Todas las variables fueron encontradas.")

else:

    print("Variables faltantes:")

    print(faltantes)

==========================================================================================
VALIDACIÓN
==========================================================================================

Todas las variables fueron encontradas.

In [8]:
#==========================================================================================
# CONSTRUCCIÓN DEL DATASET
#==========================================================================================

dataset_ml = dataset[lista_variables].copy()

print()

print("="*90)
print("DATASET OPTIMIZADO")
print("="*90)

print()

print(f"Observaciones : {dataset_ml.shape[0]}")

print(f"Variables     : {dataset_ml.shape[1]}")

display(dataset_ml.head())

==========================================================================================
DATASET OPTIMIZADO
==========================================================================================

Observaciones : 528
Variables     : 9

,Precipitacion_mm,ONI,Radiacion_Solar,Humedad_Relativa,Temp_Min_C,Mes,Velocidad_Viento,irca,VolumenUtilDiarioMasa
0,2.70,0.68,17.78,77.88,8.45,1,1.37,0,0
1,2.22,0.57,17.16,78.83,13.72,2,1.14,0,0
2,5.25,0.57,16.63,80.28,13.52,3,1.09,0,0
3,6.16,0.82,16.56,80.32,12.81,4,1.07,0,0
4,3.27,1.03,16.00,79.57,12.24,5,1.14,0,0

In [9]:
#==========================================================================================
# DIAGNÓSTICO GENERAL
#==========================================================================================

print()

print("="*90)
print("DIAGNÓSTICO")
print("="*90)

print()

print("Valores faltantes")

display(dataset_ml.isnull().sum())

print()

print("Duplicados")

print(dataset_ml.duplicated().sum())

==========================================================================================
DIAGNÓSTICO
==========================================================================================

Valores faltantes

Precipitacion_mm         0
ONI                      0
Radiacion_Solar          0
Humedad_Relativa         0
Temp_Min_C               0
Mes                      0
Velocidad_Viento         0
irca                     0
VolumenUtilDiarioMasa    0
dtype: int64

Duplicados
0

In [10]:
#==========================================================================================
# RESUMEN ESTADÍSTICO
#==========================================================================================

display(

    dataset_ml.describe().T

)

,count,mean,std,min,25%,50%,75%,max
Precipitacion_mm,528.0,6.066307,3.708268,0.00,3.0850,5.845,8.3725,18.32
ONI,528.0,0.166364,0.938824,-1.36,-0.5525,-0.015,0.6650,2.77
Radiacion_Solar,528.0,16.586723,1.696319,11.97,15.4575,16.495,17.5025,22.33
Humedad_Relativa,528.0,84.681875,5.181825,65.84,81.5600,86.200,88.5400,92.16
Temp_Min_C,528.0,11.102652,2.474984,4.13,9.1850,11.260,13.1425,16.67
Mes,528.0,6.500000,3.455326,1.00,3.7500,6.500,9.2500,12.00
Velocidad_Viento,528.0,1.092746,0.261388,0.48,0.9000,1.030,1.2600,1.88
irca,528.0,0.090909,0.287752,0.00,0.0000,0.000,0.0000,1.00
VolumenUtilDiarioMasa,528.0,0.083333,0.276648,0.00,0.0000,0.000,0.0000,1.00

In [11]:
#==========================================================================================
# EXPORTACIÓN
#==========================================================================================

import os
from pathlib import Path

ruta_str = "Preparacion_Machine_Learning/dataset_machine_learning/"

# Crear el directorio si no existe
ruta = Path(ruta_str)
ruta.mkdir(parents=True, exist_ok=True)

dataset_ml.to_parquet(

    ruta / "dataset_machine_learning.parquet",

    index=False

)

dataset_ml.to_csv(

    ruta / "dataset_machine_learning.csv",

    index=False,

    encoding="utf-8-sig"

)

dataset_ml.to_excel(

    ruta / "dataset_machine_learning.xlsx",

    index=False

)

print()

print("="*90)
print("ARCHIVOS GENERADOS")
print("="*90)

print()

print("dataset_machine_learning.parquet")

print("dataset_machine_learning.csv")

print("dataset_machine_learning.xlsx")

==========================================================================================
ARCHIVOS GENERADOS
==========================================================================================

dataset_machine_learning.parquet
dataset_machine_learning.csv
dataset_machine_learning.xlsx